website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    user_accounts = db.relationship('Accounts')

class Accounts(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True)
    password = db.Column(db.String(100))
    phone = db.Column(db.String(20), unique=True)
    allowed_accounts = db.Column(db.String(100), unique=True)
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return f'<User: {self.username}>'

if __name__ == '__main__':
    Accounts.authenticate('Vin')

website/__init__.py
import imp
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'Kenya@2030'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User, Accounts

    create_database(app)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app


def create_database(app):
    if not path.exists('website/' + DB_NAME):
        with app.app_context():
            db.create_all(app=app)
            print('Created Database!')

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                #flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(
                password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))

    return render_template("sign_up.html", user=current_user)

website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for
from flask_login import login_required, current_user
from .models import Accounts
from . import db
import json
import threading


views = Blueprint('views', __name__)


@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    return render_template("home.html", user=current_user)

@views.route('/add_user', methods=['GET', 'POST'])
@login_required
def add_user():
    if request.method == 'POST':
        id = request.form.get('id')
        username = request.form.get('userName')
        password = request.form.get('password')
        phone = request.form.get('phone')
        allowed_accounts = request.form.get('allowed_accounts')

        account = Accounts.query.filter_by(username=username).first()
        phone_exists = Accounts.query.filter_by(phone=phone).first()
        if account:
            flash('User already Exists!', category='error')
        elif phone_exists:
            flash('Phone number already taken!', category='error')
        else:
            new_account = Accounts(id=id, username=username, password=password, phone=phone, allowed_accounts=allowed_accounts, user_id=current_user.id)
            db.session.add(new_account)
            db.session.commit()
            flash('New Account added!', category='success')


    return render_template("add_user.html", user=current_user)

@views.route('/user_profile', methods=['GET', 'POST'])
@login_required
def user_profiles():
    
    return render_template("user_profile.html", user=current_user)

    
@views.route('/delete-account', methods=['GET', 'POST'])
@login_required
def delete_account():
    account_id = request.form.get("delete")
    account = db.session.query(Accounts).filter(Accounts.id==account_id).first()
    if account:
        db.session.delete(account)
        db.session.commit()
        flash('Account deleted!', category='success')
    else:
        flash(f'Account { account_id } not found!', category='error')

    return render_template("user_profile.html", user=current_user)


@views.route('/api', methods=['GET', 'POST'])
@login_required
def api():
    return render_template("api.html", user=current_user)

#Scripty server
@views.route('/server', methods=['GET', 'POST'])
def server():
    from .server import Server
    if request.method == 'POST':
        try:
            server = Server()
            thread1 = threading.Thread(target=server.run)
            thread1.start()
            flash(f'Server started on { server.SERVER }', category='success')
        except Exception as E:
            print(E)
            flash(f'Server is already running', category='error')
    
    return render_template("server.html", user=current_user)


# API endpoint
@views.route('/api/v1/users/<string:phone>', methods=['GET', 'POST'])
def get_users_by_phone(phone):
    accounts = db.Table("Accounts", db.metadata, autoload=True, autoload_with=db.engine)
    try:
        account_exists = list(db.session.query(accounts).filter_by(phone=phone).first())
        print(account_exists)
        status = 'exists'
        user_data = jsonify({"Users":db.session.query(accounts).filter_by(phone=phone).first()})
        return user_data
    except:
        print('Account doesn\'t exist')
        status = 'null'
        return status


    
        

website/templates/add_user.html
{% extends "base.html" %} {% block title %} Add User {% endblock %} {% block content
    %}
    <br/>
    <form method="POST">
      <h3 align="center">Add User</h3>
      <div class="form-group">
        <label for="userName">Username</label>
        <input
          type="userName"
          class="form-control"
          id="userName"
          name="userName"
          placeholder="Enter username"
        />
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input
          type="password"
          class="form-control"
          id="password"
          name="password"
          placeholder="Enter password"
        />
      </div>
      <div class="form-group">
        <label for="phone">Phone Number</label>
        <input
          type="phone"
          class="form-control"
          id="phone"
          name="phone"
          placeholder="Enter Phone Number (+254)"
        />
      </div>
      <div class="form-group">
        <label for="accounts">Allowed Accounts</label>
        <input
          type="allowed_accounts"
          class="form-control"
          id="allowed_accounts"
          name="allowed_accounts"
          placeholder="Allowed Usernames"
        />
      </div>
      <br />
      <div class="col text-center">
        <button type="submit" class="btn btn-primary">Add</button>
      </div>
    </form>
    {% endblock %}

website/templates/api.html
{% extends "base.html" %} {% block title %}Api{% endblock %} {% block content
    %}
    <br/>
    <h3 align="center">Welcome to Scripty API</h3>
    <div class="api">

        <a> <h5>Loading...</h5><i class="fa fa-cog fa-spin" align="center"></i></a>
    </div>
    


{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <link
     rel="stylesheet"
     type="text/css" 
     href="{{url_for('static',filename = 'style.css')}}"
     
    />
 

    <title>{% block title %} Home {% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-fixed-top navbar-expand-lg navbar-dark" style="background-color: #1e1e1f;">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar navbar-inverse">
          <li>
            <a class="navbar-brand nav-link text-light" id="home" href="/">
              <img src="{{url_for('static',filename = 'images/logo.png')}}"  alt="" width="50" height="50" class="d-inline-block align-text-top">
            </a> 
          </li> 
          {% if user.is_authenticated %}
          <ul class="nav navbar-nav navbar-right"></ul>
            <a class="navbar-nav nav-link text-white" id="user-profile" href="/user_profile">User Profiles</a>
            <a class="nav-item nav-link text-white" id="add-user" href="/add_user">Add Users</a>
            <a class="nav-item nav-link text-white" id="home" href="/api">API</a>
            <a class="nav-item nav-link text-white" id="payments" href="#">Payments</a>
            <a class="nav-item nav-link text-white" id="payments" href="/server">Server</a>
            <a class="nav navbar-nav navbar-right nav-item nav-link text-white" id="logout" href="/logout">Logout</a>
        
          </ul> 
          {% else %}
          <a class="nav-item nav-link text-white" id="login" href="/login">Login</a>
          <!-- <a class="nav-item nav-link text-white" id="signUp" href="/sign-up">Sign Up</a> -->
          {% endif %}
        </div>
      </div>
      <br/><br/>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category == 'error' %}
    <div id="alert" class="alert alert-danger alert-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div id='alert' class="alert alert-success altert-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <br/><br/><br/><br/><br/>
    <footer class="footer" style="background-color: #3a3a42;">
    </br>
      <p>
        <a href="">Support |</a>
        <a href=""> Privacy Policy |</a>
        <a href=""> Terms of Service</a>
      </p>
      
      <p>Scripty © 2022.</p>
    </footer>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <script type="text/javascript">
      window.setTimeout(function() {
          $('.alert').fadeOut('slow');
      }, 3000); 
    </script>
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
  </body>
</html>

website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
    %}
    <br/>
    <h1 align="center">Admin Dashboard</h1>
  
    <ul class="list-group list-group-flush" id="usernames">
      {% for username in user.usernames %}

      {% endfor %}
      
    </ul>
    
    {% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
    %}
    <form method="POST">
      <br/><br/><br/><br/><br/>
      <h3 align="center">Login</h3>
      <div class="form-group" align="center">
        <br/> 
        <!-- <label for="email"><strong>Email Address</strong></label> -->
        <input
          type="email"
          class="form-control col-xs-4 col-sm-4 col-md-4 col-lg-4"
          id="email"
          name="email"
          placeholder="Enter email"
        />
      </div>
      <div class="form-group" align="center">
        <!-- <label for="password"><strong>Password</strong></label> -->
        <input
          type="password"
          class="form-control col-xs-4 col-sm-4 col-md-4 col-lg-4"
          id="password"
          name="password"
          placeholder="Enter password"
        />
      </div>
      <div class="col text-center">
        <button type="submit" class="btn btn-primary active">Login</button>
      </div>
    </form>
    {% endblock %}

website/templates/my_users.html
{% extends "base.html" %} {% block title %}Add User{% endblock %} {% block content
    %}
    <h1 align="center">Add usernames</h1>
    <ul class="list-group list-group-flush" id="usernames">
      {% for username in user.usernames %}
      <li class="list-group-item">
        {{ username.data }}
        <button type="button" class="close" onClick="deleteNote({{ username.id }})">
          <span aria-hidden="true">&times;</span>
        </button>
      </li>
      {% endfor %}
    </ul>
    <form method="POST">
      <textarea name="username" id="username" class="form-control"></textarea>
      <br />
      <textarea name="password" id="password" class="form-control"></textarea>
      <br />
      <textarea name="phone" id="phone" class="form-control"></textarea>
      <br />
      <div align="center">
        <button type="submit" class="btn btn-primary">Add</button>
      </div>
    </form>
    {% endblock %}

website/templates/server.html
{% extends "base.html" %} {% block title %}Server{% endblock %} {% block content
    %}
    <br/>
    <form method="POST">
        <h3 align="center">Scripty Server</h3>
        <div class="server">
            <div class="col text-center">
                <button type="submit" class="btn btn-primary">Start</button>
            </div>
        </div>
        <br/>
    </form>
    <div align="center">
        <h5 align="center">Logs</h5>
        <textarea class='logs' id="logs" name="w3review" rows="10" cols="100">
           
        </textarea>
    </div>
    <form method="GET">
            <div class="col text-center">
                <button type="submit" class="btn btn-danger">Stop</button>
            </div>          
    </form>
    
    


{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
    content %}
    <br/>
    <form method="POST">
      <h3 align="center">Sign Up</h3>
      <div class="form-group">
        <label for="email">Email Address</label>
        <input
          type="email"
          class="form-control"
          id="email"
          name="email"
          placeholder="Enter email"
        />
      </div>
      <div class="form-group">
        <label for="firstName">First Name</label>
        <input
          type="text"
          class="form-control"
          id="firstName"
          name="firstName"
          placeholder="Enter first name"
        />
      </div>
      <div class="form-group">
        <label for="password1">Password</label>
        <input
          type="password"
          class="form-control"
          id="password1"
          name="password1"
          placeholder="Enter password"
        />
      </div>
      <div class="form-group">
        <label for="password2">Password (Confirm)</label>
        <input
          type="password"
          class="form-control"
          id="password2"
          name="password2"
          placeholder="Confirm password"
        />
      </div>
      <br />
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    {% endblock %}

website/templates/user_profile.html
{% extends "base.html" %} {% block title %} User Profile{% endblock %} {% block content
    %}
    <br/>
    <h3 align="center">Current User Profiles</h3>
    <br/>
      
    <ul class="list-group list-group-flush" id="user_accounts">
      
      <table class="table table-hover">
        <thead>
          <tr>
            <th>User ID</th>
            <th>Username</th>
            <th>Phone Number</th>
            <th>Password</th>
            <th>Date Added</th>
            <th>Allowed Usernames</th>
            <th>Payment Status</th>
            <th>Actions</th>
            <th></th>
          </tr>
        </thead>
        {% for user_account in user.user_accounts %}

        <tbody>
            <tr>
              <td> {{ user_account.id }} </td>
              <td> {{ user_account.username }} </td>
              <td> {{ user_account.phone }} </td>
              <td> {{ user_account.password}} </td>
              <td> {{ user_account.date}} </td>
              <td> {{ user_account.allowed_accounts }} </td>
              <td> {{ user_account.payment_status}} </td>  
              <td><form action="" method="POST"
                onclick="return confirm('Do you want to Suspend {{ user_account.username }}?');" title="Suspend Account">
                <button method="POST" type="submit" name="suspend" value="{{user_account['id']}}" class="btn btn-sm btn-secondary">Suspend</button>
                </form>
              </td>
              <td><form action="{{ url_for('views.delete_account', account_id=user_account.id) }}" method="POST"
                onclick="return confirm('Do you want to permanently delete {{ user_account.username }}, account id {{ user_account.id }}?');" title="Delete Account">
                <button method="POST" type="submit" name="delete" value="{{user_account['id']}}" class="btn btn-sm btn-danger">Delete</button>
              </form>
              </td> 
            </tr>
        </tbody>


        {% endfor %}
      </table>
              
     
      
    </ul>
    
    {% endblock %}